### ISSUE TITLE
allwinner: extend supported CPUS (H2, H3)

### ISSUE THREAD

**Issue by chenjeff622** [periph/host#1]
as title. how do i porting please?

**Comment by maruel** [comment]
Could you contribute one?

If you want the headers, you could create a directory orangepi and use https://github.com/periph/host/tree/main/pine64 as an inspiration, then send a PR.

**Comment by chenjeff622** [comment]
okey. i will give a try.

**Comment by f0086** [comment]
@chenjeff622 Any progress on this? If not, I could pick this one up.
I want to support the Orange Pi Zero (v1) with an Allwinner H2 CPU. Sadly, the ```allwinner``` package does not detect the CPU (see here the [detection logic](https://github.com/periph/host/blob/main/allwinner/detect.go#L71-L81)). The H2 is a 32 bit CPU with the device string ```allwinner,sun8i-h2-plus```. Can I just extend the check for this type to support the CPU or is there more work to be done? What do you think @maruel?

**Comment by chenjeff622** [comment]
https://github.com/periph/host/tree/main/allwinner
You should to create h2 inside the folder. I don't have time to test my h3 board. Maybe we make it success together.

**Comment by maruel** [comment]
Even if the pinout is not supported, you can still use sysfs driver as a fallback.
I'm happy to have more memory registered driver! I don't have one to develop and test on.
