### ISSUE TITLE
allwinner: pull-up registers not set correctly

### ISSUE THREAD

**Issue by TzeWey** [periph/host#19]
**Describe the bug**
While implementing Allwinner H5, it was discovered that the pull-up registers were not configured correctly.

**To Reproduce**
1. Run the program
```go
package main

import (
  "periph.io/x/host/v3"
)

func main() {
  host.Init()
  btn1 := gpioreg.ByName("PA13")
  btn1.In(gpio.PullUp, gpio.NoEdge)

  btn2 := gpioreg.ByName("PA14")
  btn2.In(gpio.PullUp, gpio.NoEdge)
}
```
2. Run it.
3. Check register at 0x01C2081C

**Expected behavior**
Expect 0x01C2081C to be 0x5000000

**Platform (please complete the following information):**
 - OS: Buildroot 2022.08.1
 - Board: NanoPi NEO Core2

**Additional context**
The issue appears to be caused by an implementation bug; will raise a pull request to resolve it.

**Comment by maruel** [comment]
Dang, thanks!
